{{- if .Values.openshift -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "customerSimulation.name" . }}-external
  labels:
    {{- include "customerSimulation.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "customerSimulation.serviceName" . }}
{{ end }}
