apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.postgresDB | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.postgresPassword | b64enc }}
