{{- if .Values.postgres.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "recommendation.serviceAccountName" . }}
  labels:
    {{- include "recommendation.labels" . | nindent 4 }}
  {{- with .Values.recommendationService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
