apiVersion: v1
kind: Service
metadata:
  name: {{ include "recommendation.serviceName" . }}
  labels:
    {{- include "recommendation.labels" . | nindent 4 }}
spec:
  type: {{  .Values.recommendationService.serviceType | default "ClusterIP "}}
  ports:
  - name: http
    port: {{ include "recommendation.servicePort" . }}
    targetPort: 80
  selector:
    {{- include "recommendation.selectorLabels" . | nindent 4 }}
