apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "decision.labels" . | nindent 4 }}
  name: {{ include "decision.name" . }}
  
spec:
  replicas: {{ .Values.decisionService.replicas }}
  selector:
    matchLabels:
    {{- include "decision.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "decision.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "decision.serviceAccountName" . }}
      containers:
      - name: decision-service
        image: {{ .Values.decisionService.image }}
        env:
        {{- if and .Values.decisionService.fastApi  }}
        {{- range .Values.decisionService.fastApi.env }}
        - name: {{ .name }}
          value: {{ .value | quote}}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /hello
            port: 80
