{{- if .Values.globalInfra.mqtt.sslEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-broker-ca
  labels:
    {{- include "global.labels" . | nindent 4 }}
type: Generic
data:
  broker_ca.crt: {{ .Values.globalInfra.mqtt.sslBrokerCaCertPath | .Files.Get | b64enc }}
{{ end }}