---
apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
 name: ex-aao
spec:
  deploymentPlan:
    size: 3
    image: registry.redhat.io/amq7/amq-broker:7.6
    requireLogin: false
  adminUser: admin
  adminPassword: admin
  console:
    expose: true
  acceptors:
  - name: mqtt
    protocols: mqtt
    port: 1883
    sslEnabled: false
    verifyHost: false
    expose: true