{{- if .Values.openshift -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: retail-store-web-app
  labels:
    {{- include "visualization.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "visualization.serviceName" . }}
{{ end }}
